name: 拉取镜像推送

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: '原镜像名称:版本'
        required: true
        default: 'altran1502/immich-server:v1.106.4'
      NEW_NAME:
        description: '同步后镜像名称:版本'
        required: true
        default: 'immich-server:v1.106.4'
      ARCH:
        description: '系统架构'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64
          - arm/v7
          - arm/v6
          - 386
          - s390x
          - ppc64le

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 登录到阿里云 ACR 
        id: login
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ secrets.ALI_REGISTRY }} 
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}
          logout: false 

      - name: 检查 Docker 登录成功
        if: ${{ steps.login.outcome == 'success' }}
        run: echo "Docker 登录成功"

      - name: 检查 Docker 登录失败
        if: ${{ steps.login.outcome != 'success' }}
        run: echo "Docker 登录失败"

      - name: Skopeo 同步镜像 
        id: Skopeo 
        run: |
          #!/usr/bin/env bash
          skopeo copy docker://docker.io/${{ github.event.inputs.IMAGE_NAME }} docker://${{ secrets.ALI_REGISTRY }}/cri/${{ github.event.inputs.NEW_NAME }}
        continue-on-error: true

      - name: 检查镜像推送成功
        if: ${{ steps.Skopeo.outcome == 'success' }}
        run: echo "Docker 镜像推送成功"

      - name: 检查镜像推送失败
        if: ${{ steps.Skopeo.outcome != 'success' }}
        run: echo "Docker 镜像推送失败"
